### ISSUE TITLE
3d

### ISSUE THREAD

**Issue by schell** [ublubu/shapes#25]
I know shapes is 2d and that 3d isn't on the roadmap, but how much more work is adding a separate 3d module? Maybe only using boxes or spheres?

**Comment by ublubu** [comment]
Finding contacts between shapes is more complicated in 3D, but there isn't a big difference otherwise. However, the stuff that's the same isn't currently in a state where code could be shared between 2D and 3D.

On the one hand, there's a lot more I think I need to add to the 2D engine. On the other hand, I prefer 3D games. It might not be crazy to pivot at some point.
