### ISSUE TITLE
Publish to hackage

### ISSUE THREAD

**Issue by Fresheyeball** [ublubu/shapes#26]
This would make using this library more discover-able.

**Comment by ublubu** [comment]
Oh hello! I'd kinda stepped away from this project since I've been busy, but that's a good idea.

I'm not sure people should be using it right now since I won't be using it for anything myself until after my current side project stabilizes. There are a few things (tree-based broadphase culling) I need to add before it can really be useful.

**Comment by fgaz** [comment]
Just mark it as experimental and set the version to 0.x... there's a lot of experimental packages in hackage

**Comment by schell** [comment]
PR's are very welcome :)

**Comment by ublubu** [comment]
Hi everyone,

I can't say I'll have time to maintain this project any time soon. I just started working full-time on my own startup, and tbh I didn't even find time for this when I was a normal Googler.

With that said, I'm happy to hand `shapes` over to someone interested in taking care of it.
I'll be back one day to publish it and add those features, but not right now.

/Kynan

**Comment by schell** [comment]
@ublubu congrats on your startup :) What it is?

I'll take hackage responsibilities for this project (if you like) and we can keep the repo here, just make me a collaborator and I'll manage it.

**Comment by ublubu** [comment]
Thanks! Essentially, we're making Ops concerns programmable in Kubernetes. It'll be a layer on top of Kubernetes that lets you develop and manage a distributed application like it's a single program.
